#!/usr/bin/env Rscript
# =============================================================================
# Job 7: Visualization — Generate All Plots
# =============================================================================
# Generates all 14 visualization plots using data from HDFS (pulled via rhdfs)
# and local R statistical results. Each plot corresponds to one from the
# original statistical_analysis.R script.
#
# Plots generated:
#   1. delay_distributions.png    — Boxplots of delay types by airline
#   2. anova_carrier_delay.png    — ANOVA boxplot with jittered points
#   3. wilcoxon_comparison.png    — Violin + boxplot for Delta vs United
#   4. dendrogram.png             — Hierarchical clustering (all flights sample)
#   5. airline_dendrogram.png     — Hierarchical clustering (airline means)
#   6. elbow_plot.png             — Elbow method for k-means
#   7. silhouette_plot.png        — Silhouette method for k-means
#   8. kmeans_airlines.png        — K-means on airline profiles
#   9. kmeans_flights.png         — K-means on flight-level sample
#  10. airline_heatmap.png        — Heatmap of airline delay profiles
#  11. regression_diagnostics.png — 4-panel LM diagnostics
#  12. regression_plot.png        — Regression scatterplot
#  13. logistic_regression_plot.png — Logistic probability curve
#  14. roc_curve.png              — ROC curve with AUC
#
# Note: Plots 5-12 and 13-14 are already generated by Jobs 4, 5, and 6.
# This script generates plots 1-3 and 4 (dendrogram of all flights).
# =============================================================================

source("src/lib/mr_helpers.R")
library(rhdfs)
hdfs.init()

section_header("Job 7: Visualization — Generating All Plots")

ensure_local_dir("output/plots")

# Load the dataset locally for visualization
# (For 33K rows, reading locally is faster than HDFS for plotting)
cat("  Loading dataset for visualization...\n")
df <- read.csv("airline_stats.csv", stringsAsFactors = FALSE)
df <- na.omit(df)
df$airline <- as.factor(df$airline)
cat(sprintf("  Loaded %d rows\n", nrow(df)))

# =============================================================================
# Plot 1: Delay Distributions (Boxplots by Airline and Delay Type)
# =============================================================================

cat("\n  Generating Plot 1: delay_distributions.png\n")

if (requireNamespace("ggplot2", quietly = TRUE) &&
    requireNamespace("tidyr", quietly = TRUE)) {

  plot_df <- tidyr::pivot_longer(
    df,
    cols = c("pct_carrier_delay", "pct_atc_delay", "pct_weather_delay"),
    names_to = "delay_type",
    values_to = "percentage"
  )

  plot_df$delay_type <- factor(
    gsub("pct_", "", gsub("_", " ", plot_df$delay_type)),
    levels = c("carrier delay", "atc delay", "weather delay")
  )

  p1 <- ggplot2::ggplot(plot_df,
                         ggplot2::aes(x = airline, y = percentage, fill = delay_type)) +
    ggplot2::geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.2) +
    ggplot2::facet_wrap(~delay_type, scales = "free_y", ncol = 1) +
    ggplot2::labs(
      title = "Delay Distributions by Airline and Type",
      x = "Airline", y = "Delay Percentage (%)", fill = "Delay Type"
    ) +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, size = 7),
      legend.position = "none"
    )

  ggplot2::ggsave("output/plots/delay_distributions.png", p1,
                  width = 12, height = 10, dpi = 150)
  cat("  Saved: output/plots/delay_distributions.png\n")
}

# =============================================================================
# Plot 2: ANOVA Boxplot (Carrier Delay by Airline)
# =============================================================================

cat("  Generating Plot 2: anova_carrier_delay.png\n")

if (requireNamespace("ggplot2", quietly = TRUE)) {
  p2 <- ggplot2::ggplot(df, ggplot2::aes(x = airline, y = pct_carrier_delay,
                                           fill = airline)) +
    ggplot2::geom_boxplot(outlier.size = 0.3, outlier.alpha = 0.1) +
    ggplot2::geom_jitter(width = 0.2, alpha = 0.02, size = 0.3) +
    ggplot2::labs(
      title = "ANOVA: Carrier Delay by Airline",
      subtitle = "Boxplots with jittered data points",
      x = "Airline", y = "Carrier Delay (%)"
    ) +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, size = 7),
      legend.position = "none"
    )

  ggplot2::ggsave("output/plots/anova_carrier_delay.png", p2,
                  width = 10, height = 6, dpi = 150)
  cat("  Saved: output/plots/anova_carrier_delay.png\n")
}

# =============================================================================
# Plot 3: Wilcoxon Comparison (Violin + Boxplot for Delta vs United)
# =============================================================================

cat("  Generating Plot 3: wilcoxon_comparison.png\n")

if (requireNamespace("ggplot2", quietly = TRUE)) {
  wilcox_data <- df[df$airline %in% c("Delta", "United"), ]

  if (nrow(wilcox_data) > 0) {
    wilcox_data$airline <- factor(wilcox_data$airline)

    p3 <- ggplot2::ggplot(wilcox_data,
                           ggplot2::aes(x = airline, y = pct_carrier_delay,
                                        fill = airline)) +
      ggplot2::geom_violin(alpha = 0.3, trim = TRUE) +
      ggplot2::geom_boxplot(width = 0.2, outlier.size = 0.5) +
      ggplot2::labs(
        title = "Wilcoxon Rank-Sum Test: Delta vs United",
        subtitle = "Carrier Delay Distribution Comparison",
        x = "Airline", y = "Carrier Delay (%)"
      ) +
      ggplot2::theme_minimal() +
      ggplot2::theme(legend.position = "none")

    ggplot2::ggsave("output/plots/wilcoxon_comparison.png", p3,
                    width = 7, height = 5, dpi = 150)
    cat("  Saved: output/plots/wilcoxon_comparison.png\n")
  } else {
    cat("  WARNING: No Delta/United data found. Skipping.\n")
  }
}

# =============================================================================
# Plot 4: Dendrogram of All Flights (Sampled)
# =============================================================================

cat("  Generating Plot 4: dendrogram.png\n")

set.seed(42)
sample_size <- min(3000, nrow(df))
flight_sample <- df[sample(nrow(df), sample_size),
                     c("pct_carrier_delay", "pct_atc_delay", "pct_weather_delay")]
flight_scaled <- scale(flight_sample)

# Hierarchical clustering on sample
dist_sample <- dist(flight_scaled, method = "euclidean")
hc_sample <- hclust(dist_sample, method = "ward.D2")

if (requireNamespace("factoextra", quietly = TRUE)) {
  p4 <- factoextra::fviz_dend(hc_sample, k = 6,
                               cex = 0.5,
                               main = "Hierarchical Clustering of Flights (Sample)",
                               xlab = "Flights", ylab = "Height")
  ggplot2::ggsave("output/plots/dendrogram.png", p4,
                  width = 12, height = 6, dpi = 150)
} else {
  png("output/plots/dendrogram.png", width = 1200, height = 600)
  plot(hc_sample,
       main = "Hierarchical Clustering of Flights (Sample, n=3000)",
       xlab = "Flights", ylab = "Height", cex = 0.3)
  rect.hclust(hc_sample, k = 6, border = 2:7)
  dev.off()
}
cat("  Saved: output/plots/dendrogram.png\n")

# =============================================================================
# Summary of All Plots
# =============================================================================

cat("\n============================================\n")
cat("  All Plots Generated\n")
cat("============================================\n")

plot_files <- c(
  "delay_distributions.png",
  "anova_carrier_delay.png",
  "wilcoxon_comparison.png",
  "dendrogram.png",
  "airline_dendrogram.png",
  "elbow_plot.png",
  "silhouette_plot.png",
  "kmeans_airlines.png",
  "kmeans_flights.png",
  "airline_heatmap.png",
  "regression_diagnostics.png",
  "regression_plot.png",
  "logistic_regression_plot.png",
  "roc_curve.png"
)

cat("\n  Output files in output/plots/:\n")
existing <- file.exists(file.path("output/plots", plot_files))
for (i in seq_along(plot_files)) {
  status <- if (existing[i]) "OK" else "MISSING"
  cat(sprintf("    [%s] %s\n", status, plot_files[i]))
}

cat("\n  Job 7 complete.\n")
